apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-xlow
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-xlow@sha256:497c5f4d0c1604fcc4397994fa4e6677db2c693c473089de5d94d2d0d21455c4
        name: my-nodejs
        resources: {}
status: {}
